### PR TITLE
Create pages for ECO Azure Spot Policies

### PR DESCRIPTION
**Pull request by stevenfeltner**
- Created Azure ECO readonly page
- Created Azure ECO full permission page

### CODE REVIEW

**Comment by netapp-jmontel** [comment]
@bjswoboda, pls see these two pages that @stevenfeltner created. Should we have these pages? If so, please review them. Should I publish as they are or are changes required? Thx

**Comment by bjswoboda** [comment]
@netapp-jmontel we already have addressed this in https://docs.spot.io/eco/getting-started/connect-azure-ea-to-eco.
We should not publish Steven's pages.

**Comment by stevenfeltner** [comment]
@bjswoboda The feedback we received from customers is that they would like a separate page for the policies so that it's easier to send to security teams for review and approval. Today it's hidden within the doc, where you can easily pass over it as it's not expanded by default. We are looking to replicate the structure we have for AWS for Azure and publish individual separate pages just for the policy.

**Comment by bjswoboda** [comment]
@stevenfeltner Andy has addressed this in the new version. Only the read permissions are shown in public documentation

**Pull request closed without merging**
